### ISSUE TITLE
h5zhifu.com - 推荐使用这个真正的个人支付接口，全场景支持，支持pc扫码、微信浏览器、手机H5端支付

### ISSUE THREAD

**Issue by opppp8** [Tai7sy/card-system#390]
目前支持风铃card-system发卡，全场景支持，支持pc扫码、微信浏览器、手机H5端支付，顾客体验好：https://h5zhifu.com

**Comment by shaoyingrui** [comment]
说支持，开户收费，结果插件还收费。。。不是不在列表的才收费么？。。。。

**Comment by 2399483979** [comment]
易支付：yzf.jvhezs.com
（不用挂机，但是要到凌晨才结账）
码支付http://zf.jvhezs.com/
（即时到账，但要挂机）
以上都不用身份证，营业执照注册。真正适合个人发卡网
QQ讨论群：978095958

**Comment by 2399483979** [comment]
群上面有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月4日(星期一) 晚上8:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tai7sy/card-system] h5zhifu.com - 推荐使用这个真正的个人支付接口，全场景支持，支持pc扫码、微信浏览器、手机H5端支付 (#390)





 
Closed #390.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
