### ISSUE TITLE
求一个V免签的对接api，大佬们。

### ISSUE THREAD

**Issue by fjhechuan** [Tai7sy/card-system#391]
https://github.com/szvone/Vmqphp
求一个V免签的对接api，大佬们。

**Comment by dengzhuo111** [comment]
![image](https://user-images.githubusercontent.com/69563943/114560274-1d492c80-9c9f-11eb-9aaf-2dec4d736339.png)
q2802426683

**Comment by rrkai** [comment]
这个V免签修改版的好用...
https://gitee.com/yuniks/VPAY

**Comment by fjhechuan** [comment]
> 这个V免签修改版的好用...
> https://gitee.com/yuniks/VPAY

但是这个怎么对接到风铃上呢？大佬

**Comment by Fateliu** [comment]
> 这个V免签修改版的好用...
> https://gitee.com/yuniks/VPAY

一样问 怎么对接呢

**Comment by caonima1sdo** [comment]
我可以对接v免签

**Comment by 2399483979** [comment]
易支付：http://mzf.jvhezs.com/（不用挂机，但是要到凌晨才结账）
易支付http://zf.jvhezs.com/（即时到账，但要挂机）
以上都不用身份证，营业执照注册。真正适合个人发卡网
有问题可联系我：2399483979

**Comment by 2399483979** [comment]
易支付：yzf.jvhezs.com
（不用挂机，但是要到凌晨才结账）
码支付http://zf.jvhezs.com/
（即时到账，但要挂机）
以上都不用身份证，营业执照注册。真正适合个人发卡网
QQ讨论群：978095958







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月18日(星期三) 晚上8:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tai7sy/card-system] 求一个V免签的对接api，大佬们。 (#391)





 
Closed #391.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 2399483979** [comment]
> > V 次要点， 但未包括... https://gitee.com/yuniks/VPAY
> 
> 一样问 怎么对接呢

我这可以免费帮对接
