### ISSUE TITLE
推荐一个真正的个人免签约支付接口，不用挂机，个人就可以直接使用

### ISSUE THREAD

**Issue by beifang333** [Tai7sy/card-system#392]
https://www.yunmianqian.com  只需个人微信或者支付宝账号即可自动化收款

**Comment by 2399483979** [comment]
http://mzf.jvhezs.com/

**Comment by 2399483979** [comment]
易支付：http://mzf.jvhezs.com/
（不用挂机，但是要到凌晨才结账）
码支付http://zf.jvhezs.com/
（即时到账，但要挂机）
以上都不用身份证，营业执照注册。真正适合个人发卡网
QQ讨论群：978095958

**Comment by 2399483979** [comment]
群上面有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月4日(星期一) 晚上8:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tai7sy/card-system] 推荐一个真正的个人免签约支付接口，不用挂机，个人就可以直接使用 (#392)





 
Closed #392.
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
