### ISSUE TITLE
求一个风铃对接V免签的API

### ISSUE THREAD

**Issue by 1457695165** [Tai7sy/card-system#403]
https://github.com/szvone/Vmqphp

**Comment by 2399483979** [comment]
易支付：http://mzf.jvhezs.com/
（不用挂机，但是要到凌晨才结账）
码支付http://zf.jvhezs.com/
（即时到账，但要挂机）
以上都不用身份证，营业执照注册。真正适合个人发卡网

**Comment by Tai7sy** [comment]
3.14 已加入支持, 详细参考
https://github.com/Tai7sy/card-gateway/tree/master/Pay/VPay

**Comment by 2399483979** [comment]
群上面有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年10月4日(星期一) 晚上8:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Tai7sy/card-system] 求一个风铃对接V免签的API (#403)





 
3.14 已加入支持, 详细参考
 https://github.com/Tai7sy/card-gateway/tree/master/Pay/VPay
 
&mdash;
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
